service: prism-backend-dtcc
runtime: python
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11.0"
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
handlers:
  - url: /.*
    script: auto
instance_class: F4_1G
resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 50
automatic_scaling:
  target_concurrent_requests: 10
env_variables:
  GCS_BUCKET_NAME: "chatbotstorages"
  USE_GCS: "true"
  DEV_MODE: "True"
  DATABASE_URL: "sqlite:///./prism.db"
  SUPABASE_URL: "https://xmiaviahqbbxwyuslrpe.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaWF2aWFocWJieHd5dXNscnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzY5NDIsImV4cCI6MjA1ODUxMjk0Mn0.mwDqivcJF79a1o5PDbbiUpDIixSHbnaBnUycxy33MYk"
  SUPABASE_JWT_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaWF2aWFocWJieHd5dXNscnBlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjkzNjk0MiwiZXhwIjoyMDU4NTEyOTQyfQ.88GzMjkuQIdLSlOkVWtuFl1avjAatyDc_BJYa_2uixQ"
  GOOGLE_APPLICATION_CREDENTIALS: "block-convey-p1-57b22f608952.json"
  LOG_LEVEL: "INFO"
  BACKEND_CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://localhost:8000", "https://prism.blockconvey.com", "https://ai-gov-dashboard.vercel.app", "https://api-service-blockconvey-aigovernance-dot-block-convey-p1.uc.r.appspot.com", "https://block-convey-p1.uc.r.appspot.com", "https://prism-backend-dot-block-convey-p1.uc.r.appspot.com","https://prism-backend-dtcc-dot-block-convey-p1.uc.r.appspot.com","https://dtcc-hackathon-prism.vercel.app"]'
  UPLOAD_DIR: "uploads"
  MAX_UPLOAD_SIZE: 10485760
  SECRET_KEY: "your-secret-key-here"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: 1440
  API_V1_STR: "/api/v1"
  PROJECT_NAME: "Prism Backend"
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  GOOGLE_API_KEY: "your-google-api-key"
  LOG_FORMAT: "json"
  ENABLE_RED_TEAMING: "true"
  ENABLE_BENCHMARKING: "true"
  ENABLE_AUDIT: "true"

  SUPPORTED_MODEL_TYPES: '["h5", "pkl", "pt", "pth", "onnx", "pb"]'

  SUPPORTED_DATASET_TYPES: '["csv", "parquet", "json", "jsonl"]'
  RATE_LIMIT_PER_MINUTE: 100
  RATE_LIMIT_PER_MINUTE_ANONYMOUS: 10
  ENABLE_METRICS: "true"
  METRICS_PORT: 9090
